// <auto-generated>
// Generated by FoodTypeEnumGenerator on 2025-08-14 16:36:02
// Source folder: Assets/Prefabs/Night Game/Foods
// </auto-generated>

namespace FoodsGroup
{
	public enum FoodType
	{
		Beer,
		Cake,
		Pie,
		Pizza,
	}
}