// <auto-generated>
// Generated by FoodTypeEnumGenerator on 2025-09-09 18:08:47
// Source folder: Assets/Prefabs/Night Game/Foods
// </auto-generated>

namespace FoodsGroup
{
	public enum FoodType
	{
		None,
		Cake,
		Drumstick,
		Pizza,
		Potato,
	}
}