// <auto-generated>
// Generated by FoodTypeEnumGenerator on 2025-08-22 21:58:10
// Source folder: Assets/Prefabs/Night Game/Foods
// </auto-generated>

namespace FoodsGroup
{
	public enum FoodType
	{
		Beer,
		Cake,
		Drumstick,
		Pizza,
	}
}